### PR TITLE
Bump DimensionalData to fix broadcasting 

### LINKED ISSUE #33: Poor interaction with broadcastable but not equal dimensions
There's a poor interaction between dimensions which should be broadcastable but which are not equal. For example:

```julia
julia> using AstroImages

julia> dark = AstroImage(zeros(1, 10, 10));

julia> raw = AstroImage(ones(5, 10, 10));

julia> calib = raw .- dark
ERROR: DimensionMismatch: Found both lengths 5 and 1 for X
```

this is inconvenient for working with collapsed frames (e.g., master dark frame).

### PR DESCRIPTION
**Pull request by sefffal**
Fixes #33

### CODE REVIEW

**Comment by giordano** [comment]
CompatHelper should probably be enabled on this repo?

**Comment by sefffal** [comment]
Agreed, enabled now

**Comment by sefffal** [comment]
The docs failure is specific to these changes, but I don't see it locally.

**Comment by giordano** [comment]
Are you using Julia v1.7: https://github.com/JuliaAstro/AstroImages.jl/blob/7d7cb143e37caed609b748b2097c357c53e6e72d/.github/workflows/docs.yml#L17 ?

**Comment by sefffal** [comment]
Thanks for the pointer. Looks like it affects newer Julia versions too.

I think the failure may be a result of DimensionalData's new printing format combined with RGBA elements, but I can't find a small reproducible example.
Something may be wrong with the AstroImages implementation of `DimensionalData.rebuildsliced`.

The error happens while Documenter is rendering. The relevant stack trace:
```ERROR: LoadError: BoundsError: attempt to access 2556-element Base.OneTo{Int64} at index [3588:3600]
Stacktrace:
  [1] throw_boundserror(A::Base.OneTo{Int64}, I::Tuple{UnitRange{Int64}})
    @ Base .\abstractarray.jl:691
  [2] checkbounds
    @ .\abstractarray.jl:656 [inlined]
  [3] getindex
    @ .\range.jl:918 [inlined]
  [4] getindex
    @ C:\Users\William\.julia\packages\DimensionalData\4an2r\src\LookupArrays\lookup_arrays.jl:174 [inlined]
  [5] getindex
    @ C:\Users\William\.julia\packages\DimensionalData\4an2r\src\Dimensions\indexing.jl:11 [inlined]
  [6] _slicedims
    @ C:\Users\William\.julia\packages\DimensionalData\4an2r\src\Dimensions\primitives.jl:425 [inlined]
  [7] _slicedims
    @ C:\Users\William\.julia\packages\DimensionalData\4an2r\src\Dimensions\primitives.jl:417 [inlined]
  [8] _slicedims
    @ C:\Users\William\.julia\packages\DimensionalData\4an2r\src\Dimensions\primitives.jl:418 [inlined]
  [9] _slicedims
    @ C:\Users\William\.julia\packages\DimensionalData\4an2r\src\Dimensions\primitives.jl:409 [inlined]
 [10] slicedims
    @ C:\Users\William\.julia\packages\DimensionalData\4an2r\src\Dimensions\primitives.jl:389 [inlined]
 [11] rebuildsliced (repeats 5 times)
    @ C:\Users\William\.julia\dev\AstroImages\src\AstroImages.jl:252 [inlined]
 [12] getindex
    @ C:\Users\William\.julia\packages\DimensionalData\4an2r\src\array\indexing.jl:53 [inlined]
 [13] print_matrix(io::IOContext{IOBuffer}, A::AstroImageMat{RGBA{N0f8}, Tuple{X{DimensionalData.Dimensions.LookupArrays.Sampled{Int64, Base.OneTo{Int64}, DimensionalData.Dimensions.LookupArrays.ForwardOrdered, DimensionalData.Dimensions.LookupArrays.Regular{Int64}, DimensionalData.Dimensions.LookupArrays.Points, DimensionalData.Dimensions.LookupArrays.NoMetadata}}, Y{DimensionalData.Dimensions.LookupArrays.Sampled{Int64, Base.OneTo{Int64}, DimensionalData.Dimensions.LookupArrays.ForwardOrdered, DimensionalData.Dimensions.LookupArrays.Regular{Int64}, DimensionalData.Dimensions.LookupArrays.Points, DimensionalData.Dimensions.LookupArrays.NoMetadata}}}, Tuple{}, MappedArrays.ReadonlyMultiMappedArray{RGBA{N0f8}, 2, Tuple{SubArray{Float64, 2, Matrix{Float64}, Tuple{StepRange{Int64, Int64}, Base.Slice{Base.OneTo{Int64}}}, false}, MappedArrays.ReadonlyMappedArray{Any, 2, SubArray{Float64, 2, Matrix{Float64}, Tuple{StepRange{Int64, Int64}, Base.Slice{Base.OneTo{Int64}}}, false}, AstroImages.var"#132#133"{Int64}}}, AstroImages.var"#colormap#83"{typeof(asinhstretch), ColorSchemes.ColorScheme{Vector{RGB{Float64}}, String, String}, Float64, Float64}}, Tuple{X{DimensionalData.Dimensions.LookupArrays.Sampled{Int64, Base.OneTo{Int64}, DimensionalData.Dimensions.LookupArrays.ForwardOrdered, DimensionalData.Dimensions.LookupArrays.Regular{Int64}, DimensionalData.Dimensions.LookupArrays.Points, DimensionalData.Dimensions.LookupArrays.NoMetadata}}, Y{DimensionalData.Dimensions.LookupArrays.Sampled{Int64, Base.OneTo{Int64}, DimensionalData.Dimensions.LookupArrays.ForwardOrdered, DimensionalData.Dimensions.LookupArrays.Regular{Int64}, DimensionalData.Dimensions.LookupArrays.Points, DimensionalData.Dimensions.LookupArrays.NoMetadata}}}})
    @ DimensionalData C:\Users\William\.julia\packages\DimensionalData\4an2r\src\array\show.jl:95
 [14] print_array
    @ C:\Users\William\.julia\packages\DimensionalData\4an2r\src\array\show.jl:44 [inlined]
 [15] show_after
    @ C:\Users\William\.julia\packages\DimensionalData\4an2r\src\array\show.jl:33 [inlined]
 [16] show(io::IOContext{IOBuffer}, mime::MIME{Symbol("text/plain")}, A::AstroImageMat{RGBA{N0f8}, Tuple{X{DimensionalData.Dimensions.LookupArrays.Sampled{Int64, Base.OneTo{Int64}, DimensionalData.Dimensions.LookupArrays.ForwardOrdered, DimensionalData.Dimensions.LookupArrays.Regular{Int64}, DimensionalData.Dimensions.LookupArrays.Points, DimensionalData.Dimensions.LookupArrays.NoMetadata}}, Y{DimensionalData.Dimensions.LookupArrays.Sampled{Int64, Base.OneTo{Int64}, DimensionalData.Dimensions.LookupArrays.ForwardOrdered, DimensionalData.Dimensions.LookupArrays.Regular{Int64}, DimensionalData.Dimensions.LookupArrays.Points, DimensionalData.Dimensions.LookupArrays.NoMetadata}}}, Tuple{}, MappedArrays.ReadonlyMultiMappedArray{RGBA{N0f8}, 2, Tuple{SubArray{Float64, 2, Matrix{Float64}, Tuple{StepRange{Int64, Int64}, Base.Slice{Base.OneTo{Int64}}}, false}, MappedArrays.ReadonlyMappedArray{Any, 2, SubArray{Float64, 2, Matrix{Float64}, Tuple{StepRange{Int64, Int64}, Base.Slice{Base.OneTo{Int64}}}, false}, AstroImages.var"#132#133"{Int64}}}, AstroImages.var"#colormap#83"{typeof(asinhstretch), ColorSchemes.ColorScheme{Vector{RGB{Float64}}, String, String}, Float64, Float64}}, Tuple{X{DimensionalData.Dimensions.LookupArrays.Sampled{Int64, Base.OneTo{Int64}, DimensionalData.Dimensions.LookupArrays.ForwardOrdered, DimensionalData.Dimensions.LookupArrays.Regular{Int64}, DimensionalData.Dimensions.LookupArrays.Points, DimensionalData.Dimensions.LookupArrays.NoMetadata}}, Y{DimensionalData.Dimensions.LookupArrays.Sampled{Int64, Base.OneTo{Int64}, DimensionalData.Dimensions.LookupArrays.ForwardOrdered, DimensionalData.Dimensions.LookupArrays.Regular{Int64}, DimensionalData.Dimensions.LookupArrays.Points, DimensionalData.Dimensions.LookupArrays.NoMetadata}}}})
    @ DimensionalData C:\Users\William\.julia\packages\DimensionalData\4an2r\src\array\show.jl:25
```

**Comment by sefffal** [comment]
I have narrowed down the docs issue to a small reproducer.

```julia
julia> using AstroImages
julia> d = AstroImage(randn(20,10),(X,Y));
julia> size(d')
(10, 20)
julia> size.(dims(d'))
((20,), (10,))
```
The above snippet works if AstroImage is replaced by a DimArray. 
Somehow the transpose is not applying to the dimensions, but is applying to the data.
@rafaqz do you have any ideas on where to look? I can't find what's wrong with our implementation.

This was never working correctly, but is now causing our docs build to break due to some unrelated changes in newer DimensionalData.

**Comment by rafaqz** [comment]
Ah interesting. Probably there is a mistake in the implementation of `'`

It's better to use `permutedims` unless you actually need the adjoint, as it can't be applied to some dimensions like categorical dimensions as its recursive and will fail on e.g. strings.

**Pull request merged**
